version: '2'

services:
  ldap-rfc2307:
    image: mesosphere/openldap-1.1.6:rfc2307
    environment:    
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Apache Software Foundation"
      LDAP_DOMAIN: "apache.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "servercrt.pem"
      LDAP_TLS_KEY_FILENAME: "serverkey.pem"
      LDAP_TLS_CA_CRT_FILENAME: "default-ca.pem"
      LDAP_TLS_ENFORCE: "true"           
      LDAP_TLS_VERIFY_CLIENT: "never"
      #LDAP_TLS_VERIFY_CLIENT: "allow"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      #LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_PROTOCOL_MIN: "3.0"
      #LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0" 
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      TERM: "dumb"
    tty: true
    stdin_open: true
    volumes:
      - ./certs-rfc2307:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "639:639"
    hostname: "ldap-rfc2307"
 
  sssd-rfc2307:
    build:
      context: ./build-rfc2307
    image: moresandeep/sssd-dev-rfc2307
    command: /init-rfc2307.sh
    depends_on:
      - ldap-rfc2307
    environment:    
      TLS_CACERTDIR: "/etc/openldap/certs"
      LDAPTLS_CACERT: "/etc/openldap/certs/default-ca.pem"
      TLS_REQCERT: "never"
    volumes:
      - ./conf:/knox/conf/
      - ./certs-rfc2307:/etc/openldap/certs
      #- ./logs/sssd:/var/log/sssd
    ports:
      - "8443:8443"
    